test steps

diff --git a/.github/workflows/drc.yml b/.github/workflows/drc.yml
--- a/.github/workflows/drc.yml
+++ b/.github/workflows/drc.yml
@@ -20,24 +20,20 @@ name: DRC
 on: push
 
 jobs:
-    Installing_Klayout:
-        name: Installing Klayout
+    drc:
         runs-on: ubuntu-latest
         steps:
-            - run: |
-                sudo apt update -qq -y
-                wget https://www.klayout.org/downloads/Ubuntu-22/klayout_0.29.0-1_amd64.deb
-                # The dpkg command will fail complaining about missing dependencies.
-                sudo dpkg -i ./klayout_0.29.0-1_amd64.deb || true
-                # The apt install command should install the missing dependencies
-                # needed by KLayout above and finish the install.
-                sudo apt install -f -y
-                # Check that KLayout was successfully installed!
-                klayout -v
-    Install_IHP_Open_PDK:
-        name: Install IHP_Open_PDK
-        runs-on: ubuntu-latest
-        needs: Installing_Klayout
-        steps:
-            - run: |
-                klayout -v
+            -   name: Installing Klayout
+                run: |
+                    sudo apt update -qq -y
+                    wget https://www.klayout.org/downloads/Ubuntu-22/klayout_0.29.0-1_amd64.deb
+                    # The dpkg command will fail complaining about missing dependencies.
+                    sudo dpkg -i ./klayout_0.29.0-1_amd64.deb || true
+                    # The apt install command should install the missing dependencies
+                    # needed by KLayout above and finish the install.
+                    sudo apt install -f -y
+                    # Check that KLayout was successfully installed!
+                    klayout -v
+            -   name: Install IHP_Open_PDK
+                run: |
+                    klayout -v
