try catch logic

diff --git a/.github/workflows/drc.yml b/.github/workflows/drc.yml
--- a/.github/workflows/drc.yml
+++ b/.github/workflows/drc.yml
@@ -50,5 +50,27 @@ jobs:
                     export KLAYOUT_HOME=/home/runner/work/IHP-Open-DesignLib/IHP-Open-DesignLib/Open-PDK/ihp-sg13g2/libs.tech/klayout/tech klayout
                     ls
                     pwd 
-                    klayout -b -r /home/runner/work/IHP-Open-DesignLib/IHP-Open-DesignLib/Open-PDK/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc -rd "in_gds"="/home/runner/work/IHP-Open-DesignLib/IHP-Open-DesignLib/lib/AnalogLDO_exampleDesign/design_data/klayout/gds/LDO.gds"
-                    exit 130
+                    OUTPUT=$(klayout -b -r /home/runner/work/IHP-Open-DesignLib/IHP-Open-DesignLib/Open-PDK/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc -rd "in_gds"="/home/runner/work/IHP-Open-DesignLib/IHP-Open-DesignLib/lib/AnalogLDO_exampleDesign/design_data/klayout/gds/LDO.gds")
+
+                    echo $OUTPUT
+                    re="Number of DRC errors: [0-9]+"
+                    if [[ $OUTPUT =~ $re ]]; then 
+                        echo ${BASH_REMATCH};
+                        NumberRe="[0-9]+"
+                        if [[ $BASH_REMATCH =~ $NumberRe ]]; then 
+                            if (($BASH_REMATCH == 0))
+                            then 
+                                echo "pass";
+                                exit 0
+                            else
+                                echo "fail";
+                                exit 130
+                            fi
+                        else 
+                            echo "fail";
+                            exit 130
+                        fi
+                    else
+                        echo "fail";
+                        exit 130
+                    fi
